### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by hagna** [Kha-Samples/Ploing#3]
Ploing$ node Kha/make --compile
node[7831]: ../src/node_contextify.cc:635:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x8fa0c0 node::Abort() [node]
 2: 0x8fa195  [node]
 3: 0x92e5be node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [node]
 4: 0xb8d2db  [node]
 5: 0xb8f272 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 6: 0x16053aedbe1d 
Aborted (core dumped)

I'm using Haxe Compiler 4.0.0-rc.3+e3df7a4 and node v10.16.3 on Ubuntu 16.04.

**Comment by RobDangerous** [comment]
You don't use "Haxe Compiler 4.0.0-rc.3+e3df7a4" when you use Kha, it uses its own internal version of Haxe.
But your node v10.16.3 crashes internally, try a different version.
